name: Wedding Photographer
favicon: null
layout_spectrum: 0.5554956141859293
typography_spectrum: 0.483702190220356
title: The perfect way to capture your day
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.592189779272303
  lightness: 0.00975240021944046
  saturation: 0.3335635270923376
  rhythmicContrast: 0.09214176796376705
purpose: []
