name: Wedding Photographer
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24392
title: The perfect way to capture your day
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#225a8e'
    - '#0f1215'
    - '#fcfcfc'
    - '#bdc2c2'
    - '#9b6d63'
  brandStrength: 0.5
  lightness: 0.00975240021944046
  saturation: 0.3335635270923376
  rhythmicContrast: 0.09214176796376705
purpose: []
