name: Wedding Photographer
favicon: null
layout_spectrum: 1
typography_spectrum: 0.483702190220356
title: The perfect way to capture your day
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#313625'
    - '#000000'
    - '#9cacb9'
    - '#556b80'
    - '#ced4da'
  brandStrength: 0.6875
  lightness: 0.00975240021944046
  saturation: 0.3335635270923376
  rhythmicContrast: 0.09214176796376705
purpose: []
